<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Tanyas-MacBook-Air.local" name="com.epam.testng.tests.SubLongsTest" tests="9" failures="0" timestamp="14 Dec 2017 05:58:22 GMT" time="0.005" errors="3">
  <testcase name="subPositiveLongs" time="0.000" classname="com.epam.testng.tests.SubLongsTest">
    <error type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherExceptionat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)at org.testng.internal.Invoker.invokeMethod(Invoker.java:603)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </error>
  </testcase> <!-- subPositiveLongs -->
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveLongs" time="0.000" classname="com.epam.testng.tests.SubLongsTest">
    <error type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherExceptionat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)at org.testng.internal.Invoker.invokeMethod(Invoker.java:603)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </error>
  </testcase> <!-- subPositiveLongs -->
  <testcase name="subPositiveAndNegativeLongs" time="0.000" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subPositiveLongs" time="0.000" classname="com.epam.testng.tests.SubLongsTest">
    <error type="org.testng.TestException" message="
Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.TestException: Method SubLongsTest.subPositiveLongs(long, long, long)[pri:0, instance:com.epam.testng.tests.SubLongsTest@5a42bbf4] should have thrown an exception of type class org.testng.internal.reflect.MethodMatcherExceptionat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)at org.testng.internal.Invoker.invokeMethod(Invoker.java:603)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </error>
  </testcase> <!-- subPositiveLongs -->
  <testcase name="subPositiveAndNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
  <testcase name="subNegativeLongs" time="0.001" classname="com.epam.testng.tests.SubLongsTest"/>
</testsuite> <!-- com.epam.testng.tests.SubLongsTest -->
